// resources/js/pages/Welcome.vue
<script setup lang="ts">
import { Button } from "@/components/ui/button"
import { Head } from '@inertiajs/vue3'
import { ref } from 'vue';

window.addEventListener('message', (event) => {
    console.log('event', event)
    userId.value = event.data.userId
})

const userId = ref('N/A')
</script>

<template>

    <Head title="Welcome">
    </Head>
    <div class="p-12 flex flex-col gap-4">
        <Button @click="userId = '1337'">UserID</Button>
        <div>User ID: {{ userId }}</div>
    </div>
</template>

// resources/js/pages/welcome.tsx
import { Button } from '@/components/ui/button';
import { Head } from '@inertiajs/react';
import { useState } from 'react';

export default function Welcome() {
    const [userId, setUserId] = useState('n/a');

    window.addEventListener('message', (event) => {
        setUserId(event.data.userId);
    });

    return (
        <>
            <Head title="TheIndivisuals">
                <link rel="preconnect" href="https://fonts.bunny.net" />
                <link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600" rel="stylesheet" />
            </Head>
            <div className="flex flex-col gap-4 p-12">
                <Button onClick={() => setUserId('n/a')}>Reset</Button>
                <span>UserID: {userId}</span>
            </div>
        </>
    );
}
